### ISSUE TITLE
A new tool for Named Entity Recognition would be good

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/geolocart#5]
- Because Java and R are not good friends as far as I understood.
- The current recognition is quite dependent on the sentence structure, e.g.

``` r
> text
[1] "I live in Barcelona but I was born in Vannes and I have worked in Berlin in the past."
> geolocart_locate(text)
[1] "Vannes" "Berlin"
> text <- "I live in Barcelona, Spain but I was born in Neverland and I worked in Cherrytown."
> geolocart_locate(text)
[1] "Barcelona" "Spain"     "Neverland"

```

For sentences this might mean it's better to divide them into smaller things which is possible using NLP methods. Besides, NER still recognizes imaginary places but it should not come up that often in articles.

**Comment by sckott** [comment]
Do you have any ideas in mind for new tools? i guess this in the future https://github.com/ropensci/unconf16/issues/8#issuecomment-205556034 ?

**Comment by maelle** [comment]
Yes exactly waiting for this might be the best solution!

Moreover I've been wondering whether it's easier to use Python tools than Java tools in R? For instance this looks nice https://pypi.python.org/pypi/polyglot but I don't use Python myself (and maybe I've overlooked a Java requirement).

**Comment by maelle** [comment]
Of course adding a dependency to another language only is worth it if it means getting a much better NER tool! And it'd have to work on every platform... Ah waiting for quanteda to have NER sounds like a good plan.

**Comment by sckott** [comment]
Python is doable, but still not very cross-platform I don't think, best is probably to wait for `quanteda`

**Comment by maelle** [comment]
No pressure, @kbenoit ;-)
