### ISSUE TITLE
Geoparsing affiliations

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/geolocart#6]
# Retrieving geo info from affiliations

For affiliations if they are formatted as in RISmed, it should be easy to retrieve locations.

``` r
library("RISmed")
data(myeloma)
Affiliation(myeloma)
```

Last word is a country, and before that there is the name of the city. However I wonder how many countries have the federal state name. Moreover, email addresses should be removed but since they are strings with a "@" it should be feasible.
# Getting affiliations

For RISmed, in the past there was only the affiliation of the first author
https://www.nlm.nih.gov/pubs/techbull/so13/brief/so13_author_affiliations.html
http://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.Affiliation_AD

**Comment by sckott** [comment]
is ris the same as rismed?  The crossref API gives back data on affiliations (other do as well, but im most familiar with crossref). e.g., using `rcrossref::cr_cn()`

``` r
cat(cr_cn(dois="10.1126/science.169.3946.635", "ris"))
#> TY  - JOUR
#> DO  - 10.1126/science.169.3946.635
#> UR  - http://dx.doi.org/10.1126/science.169.3946.635
#> TI  - The Structure of Ordinary Water: New data and interpretations are yielding new insights into this fascinating substance
#> T2  - Science
#> AU  - Frank, H. S.
#> PY  - 1970
#> DA  - 1970/08/14
#> PB  - American Association for the Advancement of Science (AAAS)
#> SP  - 635-641
#> IS  - 3946
#> VL  - 169
#> SN  - 0036-8075
#> SN  - 1095-9203
#> ER  - 
```

**Comment by maelle** [comment]
RISmed = "A set of tools to extract bibliographic content from the National Center for Biotechnology Information (NCBI) databases, including PubMed. The name RISmed is a portmanteau of RIS (for Research Information Systems, a common tag format for bibliographic data) and PubMed"

There was a RIS package in R at some point but it was removed from CRAN. However the author is the same as RISmed so I guess most useful things from RIS are in RISmed, and by useful things I mean not only access to PubMed but also RIS parsing.

The more I read, the more I realize a first step of geolocart development will be to have an exhaustive document about how to access literature from R and how to parse all results. Maybe I should try one literature package a day and write source(s) + output format + how difficult it is to use!

**Comment by sckott** [comment]
Okay, makes sense on RIS and RISmed
